Fix alignment warning
When cross-compiling in ptxdist with additional CFLAGS "-Wcast-align"
(we usually set this for ARMv5 targets) build fails like this [build
machine paths replaced with ***]:

  make[1]: Entering directory '***/platform-ncl/build-target/dropwatch-1.5.3'
  make  all-recursive
  make[2]: Entering directory '***/platform-ncl/build-target/dropwatch-1.5.3'
  Making all in src
  make[3]: Entering directory '***/platform-ncl/build-target/dropwatch-1.5.3/src'
    CC       main.o
  main.c: In function 'recv_netlink_message':
  main.c:297:25: error: cast increases required alignment of target type [-Werror=cast-align]
  cc1: all warnings being treated as errors
  Makefile:419: recipe for target 'main.o' failed
  make[3]: *** [main.o] Error 1
  make[3]: Leaving directory '***/platform-ncl/build-target/dropwatch-1.5.3/src'
  Makefile:429: recipe for target 'all-recursive' failed
  make[2]: *** [all-recursive] Error 1
  make[2]: Leaving directory '***/platform-ncl/build-target/dropwatch-1.5.3'
  Makefile:361: recipe for target 'all' failed
  make[1]: *** [all] Error 2
  make[1]: Leaving directory '***/platform-ncl/build-target/dropwatch-1.5.3'
  /usr/local/lib/ptxdist-2018.05.0/rules/post/ptxd_make_world_compile.make:21: recipe for target '***/platform-ncl/state/dropwatch.compile' failed
  make: *** [***/platform-ncl/state/dropwatch.compile] Error 2

The function wrap_netlink_msg() called in that line 297 is local to
main.c and only used once. The argument "buf" passed is simply assigned
to a member "msg" of the also local struct type "struct netlink_message"
which is a void pointer. Avoid that two times internal pointer casting
and assign with the target type right away lets the compiler warning
disappear.

Signed-off-by: Alexander Dahl <post@lespocky.de>